### ISSUE TITLE
ftp is unmaintained

### ISSUE THREAD

**Issue by ZetaNumbers** [vita-rust/cargo-vita#9]
https://github.com/mattnenterprise/rust-ftp/issues/115

Consider using [suppaftp](https://lib.rs/crates/suppaftp)

**Comment by nikarh** [comment]
Huh, you literally spotted that at the same time I fixed that :D #8

**Comment by ZetaNumbers** [comment]
I've noted it after looking at their doc and immediatelly finding they have no ayu theme.
